name: CI

on:
  pull_request:
    types: closed
    branches: [ master ]

jobs:
  push:
    # masterブランチMerge後に、deployment/stagingにPushする
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Push to Staging
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deployment/staging
